### ISSUE TITLE
createDevice failed!

### ISSUE THREAD

**Issue by diogoviana7** [K0IN/Drevo-Calibur-light-control#1]
![image](https://user-images.githubusercontent.com/33094729/77545793-decdad80-6ea2-11ea-90d2-23ded3c281b7.png)

It gives me a error with createDevice.

I have the DLL but the software doesn´t work for me it always says: Please insert the keyboard
That´s Why I´m searching in github ways of changing the lights...

Thanks

**Comment by K0IN** [comment]
I can't find the real Drevo calibur v1 driver (Note this only works with v1)

**Comment by K0IN** [comment]
Can u try with this file? https://mega.nz/file/vExzASrb#q6EHiK_nmsb4mB7z8xF2xIXvaSTDoOTTM6NGElUVkek
